### PR TITLE
Re-knit Workshop 1 ppt using R 4.1.0

### LINKED ISSUE #1: Workshop 1: Slide 45 - wrong data type for summary()
Current `.pptx` presentation shows `summary()`  producing erroneous output for objects of character class. Appears they've either been factorised or historic output.

Needs re-knitting the `.Rmd` using latest version of R and then re-uploading the powerpoint

### PR DESCRIPTION
**Pull request by tomlincr**
Workshop 1: Slide 45 - wrong data type for summary() #1

Current .pptx presentation shows summary() producing erroneous output for objects of character class. Appears they've either been factorised or historic output.

Needs re-knitting the .Rmd using latest version of R and then re-uploading the powerpoint

Fixes #1

### CODE REVIEW

**Comment by eturkes** [comment]
Thanks Chris, unfortunately the re-knit PowerPoint changes the size of the code section such that it now expands beyond the borders of the slide. See the attached image, where the old slides are on the left, the new on the right. This is with LibreOffice, but I notice the same problem with MS PowerPoint. I'm facing the same issue when I re-knit, so I'll look into some parameter or something we can change to correct this.

Screenshot_20210917_152156

**Comment by eturkes** [comment]
I was able to fix this by editing Images/template.pptx. I had to decrease the font size of the highest level heading in the Slide Master, then had to indent it a bit. A side effect is that now regular text in the R Markdown at the highest level heading is too small a font size. But an easy solution is to just always use a bullet when using regular text, the result looks similar to the old PowerPoints.

I'll merge this in then go ahead and recompile all the slides with the new template, making sure there is no new font wonkiness. Also editing where necessary re: always using bullets with regular text.

**Comment by tomlincr** [comment]
Thanks @eturkes, much appreciated

**Comment by RHReynolds** [comment]
Thanks both for sorting this! Much appreciated :)

**Pull request merged**
